name: CI
on:
  push:
    branches:
      - master
  pull_request: null
env:
  DO_NOT_TRACK: '1'
jobs:
  build:
    uses: abhi1693/actions/.github/workflows/node-ci.yml@59178a1adfb1547da9ba94fdd46962c510b8eb1f
    with:
      checks: '["lint", "test", "build"]'
      scripts: '{"lint": "lint", "test": "test", "build": "build"}'
      timeout-minutes: 20
      runs-on: ubuntu-latest
      node-version: '24'
      project-env: '{"DO_NOT_TRACK":"1"}'
