name: Container

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build linux/arm64
    uses: abhi1693/actions/.github/workflows/docker-build-push.yml@master
    with:
      runs-on: ubuntu-24.04-arm
      image: ghcr.io/${{ github.repository }}
      context: .
      file: Dockerfile
      platforms: linux/arm64
      cache-scope: tree-pop-arm64
      tags: |
        type=semver,pattern={{version}}
      labels: |
        org.opencontainers.image.source=https://github.com/${{ github.repository }}
        org.opencontainers.image.title=tree-pop
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
