name: Container
on:
  release:
    types:
      - published
permissions:
  contents: read
  packages: write
jobs:
  images:
    uses: abhi1693/actions/.github/workflows/container-images.yml@98222de88f6768904e43a1a92a32e2bdc9a16e4c
    with:
      manifest: .github/images.json
      publish: true
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
